output: main.o
	g++ main.o -o main

Node.o: Node.cpp
	g++ -c Node.cpp Node.h

Queue.o: Queue.cpp
	g++ -c Queue.cpp Queue.h

DoubleLinkedList.o: DoubleLinkedList.cpp
	g++ -c DoubleLinkedList.cpp DoubleLinkedList.h
 
clean:
	rm *.o output
